---

- name: Install aws load balancer controller
  gather_facts: false
  hosts: localhost
  vars:
    CLUSTER_NAME: "YOUR-CLUSTER-NAME"
    AWS_REGION: us-west-1

  tasks:
    - name: Download policy
      shell: |
        curl -O https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.13.0/docs/install/iam_policy.json
      register: load_balancer_policy

    - name: Create Policy
      shell: |
        aws iam create-policy \
        --policy-name AWSLoadBalancerControllerIAMPolicy \
        --policy-document '{{load_balancer_policy.stdout}}'

    - name: IRSA
      shell: |
        eksctl create iamserviceaccount \
            --cluster={{CLUSTER_NAME}} \
            --namespace=kube-system \
            --name=aws-load-balancer-controller \
            --attach-policy-arn=arn:aws:iam::<AWS_ACCOUNT_ID>:policy/AWSLoadBalancerControllerIAMPolicy \
            --override-existing-serviceaccounts \
            --region {{AWS_REGION}}\
            --approve

    - name: helm repo add
      shell: |
        helm repo add eks https://aws.github.io/eks-charts
        helm repo update eks

    - name: Helm install
      shell: |
        helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
        -n kube-system \
        --set clusterName={{CLUSTER_NAME}} \
        --set region={{AWS_REGION}}\
        --set vpcId={{AWS_VPC_ID}}
        --set serviceAccount.create=false \
        --set serviceAccount.name=aws-load-balancer-controller \
        --version 1.13.0